-- ============================================================================
-- Snigdha Chandra Paik — Portfolio Supabase Schema
-- ----------------------------------------------------------------------------
-- Paste this entire file into the Supabase SQL Editor and run it once.
-- It is idempotent: safe to re-run if you tweak it.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABLE: projects
-- ----------------------------------------------------------------------------
create table if not exists public.projects (
  id            bigint generated by default as identity primary key,
  slug          text not null unique,
  title         text not null,
  description   text not null,
  category      text not null,
  tech          text[] not null default '{}',
  image_path    text not null,                 -- storage path inside the project-images bucket, e.g. "AMJ.png"
  link               text,                          -- external live URL (nullable)
  featured           boolean not null default false,
  color_key          text,                          -- maps to src/data/colors.json keys (webflow, wordpress, shopify, ai, ...)
  case_study         text,                          -- HTML body of the case study; NULL => no /projects/<slug> page
  meta_title         text,                          -- SEO title for the /projects/<slug> case study page (optional)
  meta_description   text,                          -- SEO description for the /projects/<slug> case study page (optional)
  order_index        integer not null default 0,    -- lower = shown first
  created_at         timestamptz not null default now()
);

-- Idempotent column additions for existing installs.
alter table public.projects add column if not exists meta_title       text;
alter table public.projects add column if not exists meta_description text;

create index if not exists projects_featured_idx       on public.projects (featured);
create index if not exists projects_order_idx          on public.projects (order_index);
create index if not exists projects_has_case_study_idx on public.projects ((case_study is not null));

-- ----------------------------------------------------------------------------
-- TABLE: posts (blogs)
-- ----------------------------------------------------------------------------
create table if not exists public.posts (
  id                bigint generated by default as identity primary key,
  slug              text not null unique,
  title             text not null,
  meta_title        text,
  meta_description  text,
  category          text not null,
  date              date not null,
  image_path        text not null,             -- storage path inside the blog-images bucket
  excerpt           text not null,
  content           text not null,             -- HTML body
  created_at        timestamptz not null default now()
);

create index if not exists posts_date_idx     on public.posts (date desc);
create index if not exists posts_category_idx on public.posts (category);

-- ----------------------------------------------------------------------------
-- ROW LEVEL SECURITY — public read, no public writes
-- ----------------------------------------------------------------------------
alter table public.projects enable row level security;
alter table public.posts    enable row level security;

drop policy if exists "projects are publicly readable" on public.projects;
create policy "projects are publicly readable"
  on public.projects for select
  to anon, authenticated
  using (true);

drop policy if exists "posts are publicly readable" on public.posts;
create policy "posts are publicly readable"
  on public.posts for select
  to anon, authenticated
  using (true);

-- No INSERT/UPDATE/DELETE policies are defined for anon/authenticated.
-- Writes are performed by the Next.js admin using the service_role key,
-- which bypasses RLS, so the only path to mutate data is through the admin UI.

-- ----------------------------------------------------------------------------
-- STORAGE BUCKETS — public-read, writes via service_role only
-- ----------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
  values ('project-images', 'project-images', true)
  on conflict (id) do update set public = true;

insert into storage.buckets (id, name, public)
  values ('blog-images', 'blog-images', true)
  on conflict (id) do update set public = true;

-- Public read on both buckets
drop policy if exists "public can read project-images" on storage.objects;
create policy "public can read project-images"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'project-images');

drop policy if exists "public can read blog-images" on storage.objects;
create policy "public can read blog-images"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'blog-images');

-- No INSERT/UPDATE/DELETE policies for anon — only the service_role key can write.
